name: Provide approval for bot PRs

on:
  pull_request:

jobs:
  bot_pr_approval:
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@bot-pr-approval
    secrets: inherit
  auto-update-libs:
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@main
    secrets: inherit
